Repository Maumkkut/maumkkut_Frontend, pull requests merged in 2024-09, with the labels that each got.

#18 Feat: react-query를 적용하여 로그인 구현
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/user/index.ts
  src/hooks/queries/user.ts
  src/layout/GlobalLayout.tsx
  src/main.tsx
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
  src/types/user/index.ts
Labels: feat

#21 Feat: 커뮤니티 페이지 디자인 및 기능 구현
  index.html
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/board/index.ts
  src/api/user/index.ts
  src/assets/images/community/Hero Section.png
  src/components/Pagination/index.tsx
  src/components/community/CommentInput.tsx
  src/components/community/CommunityBoardItem.tsx
  src/components/community/CommunityComment.tsx
  src/components/community/CommunityReply.tsx
  src/constants/boardType.ts
  src/hooks/queries/board.ts
  src/hooks/queries/user.ts
  src/main.tsx
  src/pages/CommunityPage/CommunityBoard.tsx
  src/pages/CommunityPage/CommunityDetail.tsx
  src/pages/CommunityPage/CommunityPost.tsx
  src/pages/CommunityPage/index.tsx
  src/pages/LoadingPage.tsx
  src/pages/NoContents.tsx
  src/pages/NotFound.tsx
  src/pages/SigninPage.tsx
  src/pages/SocialLoadingPage.tsx
  src/router/index.tsx
  src/types/community/index.ts
  src/types/index.ts
  src/types/user/index.ts
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: feat, design

#24 Design: 단체 여행 페이지 레이아웃 작업
  src/assets/images/GroupTrip/Hero Section.svg
  src/pages/GroupTripPage/RightSideBar/GroupDetail.tsx
  src/pages/GroupTripPage/RightSideBar/GroupMake.tsx
  src/pages/GroupTripPage/RightSideBar/GroupPreview.tsx
  src/pages/GroupTripPage/RightSideBar/index.tsx
  src/pages/GroupTripPage/index.tsx
  src/router/index.tsx
Labels: design

#27 Feat: 카카오맵 모듈화 완료
  package-lock.json
  package.json
  src/assets/images/GroupTrip/Marker.svg
  src/assets/images/GroupTrip/pin.svg
  src/components/Kakaomap/index.tsx
  src/hooks/kakaomap/useKakaoLoader.tsx
  src/pages/GroupTripPage/RightSideBar/index.tsx
Labels: feat

#30 Feat: 커뮤니티 추가 구현
  .gitignore
  src/api/board/index.ts
  src/components/Header.tsx
  src/components/Pagination/index.tsx
  src/components/community/CommunityComment.tsx
  src/components/community/CommunityReply.tsx
  src/hooks/queries/board.ts
  src/pages/CommunityPage/CommunityBoard.tsx
  src/pages/CommunityPage/CommunityDetail.tsx
  src/pages/CommunityPage/index.tsx
  src/pages/SocialLoadingPage.tsx
  src/router/index.tsx
  src/types/community/index.ts
  src/types/user/index.ts
Labels: feat

#32 Fix: 렌더링 이슈 해결
  src/pages/CommunityPage/CommunityBoard.tsx
Labels: bug

#33 Fix: 렌더링 이슈 해결
  src/pages/CommunityPage/CommunityBoard.tsx
Labels: bug

#36 Design/#19 group trip design
  src/assets/images/GroupTrip/BadIcon.svg
  src/assets/images/GroupTrip/GoodColoredIcon.svg
  src/assets/images/GroupTrip/Hero Section.svg
  src/components/Kakaomap/index.tsx
  src/components/ReigonCard/index.tsx
  src/components/SearchMate/index.tsx
  src/constants/regionCode.ts
  src/pages/GroupTripPage/RightSideBar/GroupDetail.tsx
  src/pages/GroupTripPage/RightSideBar/GroupMake.tsx
  src/pages/GroupTripPage/RightSideBar/index.tsx
  src/pages/GroupTripPage/index.tsx
  src/router/index.tsx
Labels: design

#38 Fix/#37 community error
  src/components/community/CommentInput.tsx
  src/components/community/CommunityComment.tsx
  src/pages/CommunityPage/CommunityDetail.tsx
Labels: bug

#40 Design/#26 random travel destinations
  package-lock.json
  src/assets/images/RandomTravel/bike.png
  src/assets/images/RandomTravel/car.png
  src/assets/images/RandomTravel/walk.png
  src/components/Header.tsx
  src/pages/RandomTravel/CreateRandomTravel.tsx
  src/pages/RandomTravel/MyRandomTravel.tsx
  src/pages/RandomTravel/RandomTravelPage.tsx
  src/pages/TravelTasteTest/TestPage.tsx
  src/router/index.tsx
  src/store/useRTStore.ts
Labels: feat, design

#41 Design/#8 home page
  package-lock.json
  package.json
  src/assets/images/HomePage/EventInGangwon4.png
  src/assets/images/HomePage/EventInGangwon5.png
  src/assets/images/HomePage/HeroImage2.png
  src/assets/images/HomePage/HeroImage3.png
  src/assets/images/HomePage/HeroImage4.png
  src/pages/EventInGanwon.tsx
  src/pages/HomePage.tsx
  src/pages/SwiperComponent.css
Labels: feat, design

#43 Feat/#42 random travel destinations
  src/api/random/index.ts
  src/pages/RandomTravel/CreateRandomTravel.tsx
  src/pages/RandomTravel/MyRandomTravel.tsx
  src/pages/RandomTravel/RandomResult.tsx
  src/pages/RandomTravel/RandomTravelPage.tsx
  src/types/random/index.ts
Labels: feat, design

#46 Feat/#39 group make
  src/api/group/index.ts
  src/assets/images/GroupTrip/BadColoredIcon.svg
  src/assets/images/GroupTrip/GoodIcon.svg
  src/components/ReigonCard/index.tsx
  src/components/SearchMate/index.tsx
  src/hooks/queries/group.ts
  src/pages/GroupTripPage/RightSideBar/GroupDetail.tsx
  src/pages/GroupTripPage/RightSideBar/GroupMake.tsx
  src/pages/GroupTripPage/RightSideBar/index.tsx
  src/pages/GroupTripPage/index.tsx
  src/types/group/index.ts
Labels: feat, design

#48 Feat/#47 social login add info
  package-lock.json
  src/api/user/index.ts
  src/components/Header.tsx
  src/pages/Auth/AddInfoPage.tsx
  src/pages/Auth/SocialLoadingPage.tsx
  src/pages/ProfilePage/RigthSidePage/ActivityFeed.tsx
  src/pages/ProfilePage/RigthSidePage/ProfileHome.tsx
  src/types/user/index.ts
Labels: feat

#50 Feat/#45 travel taste test page
  src/api/travelTasteTest/index.ts
  src/pages/TravelTasteTest/TestDetailPage.tsx
  src/pages/TravelTasteTest/TestHistoryPage.tsx
  src/pages/TravelTasteTest/TestPage.tsx
  src/store/useTTTStore.ts
  src/types/travelTastTest/index.ts
Labels: bug, feat, design

#54 Feat/#53 discover gangwon
  src/api/discover/index.ts
  src/components/Header.tsx
  src/pages/DiscoverGangwonPage/DiscoverDetail.tsx
  src/pages/DiscoverGangwonPage/DiscoverEntry.tsx
  src/pages/DiscoverGangwonPage/DiscoverGangwonPage.tsx
  src/pages/HomePage.tsx
  src/router/index.tsx
  src/types/discover/index.ts
Labels: feat, design

#60 Feat: 여행취향테스트 QA요청사항수정
  src/pages/TravelTasteTest/TestDetailPage.tsx
  src/pages/TravelTasteTest/TestHistoryPage.tsx
Labels: bug, feat

#61 Fix: 여행취향테스트 QA요청사항수정 revert
  src/pages/TravelTasteTest/TestDetailPage.tsx
  src/pages/TravelTasteTest/TestHistoryPage.tsx
Labels: hotfix

#64 Feat/#63 로그 삭제 및 랜덤 페이지 QA 사항 변경
  src/api/random/index.ts
  src/api/travelTasteTest/index.ts
  src/pages/DiscoverGangwonPage/DiscoverDetail.tsx
  src/pages/HomePage.tsx
  src/pages/RandomTravel/CreateRandomTravel.tsx
  src/pages/RandomTravel/MyRandomTravel.tsx
  src/pages/RandomTravel/RandomResult.tsx
  src/pages/TravelTasteTest/TestDetailPage.tsx
  src/pages/TravelTasteTest/TestHistoryPage.tsx
  src/pages/TravelTasteTest/TestPage.tsx
Labels: bug, feat, design
